#!/bin/sh

sudo su -c "echo 'deb https://download.webmin.com/download/repository sarge contrib' >> /etc/apt/sources.list && cd /root && wget https://download.webmin.com/jcameron-key.asc && apt-key add jcameron-key.asc"
sudo apt-get update -y
sudo apt-get install apt-transport-https webmin -y
sudo ufw allow 10000/tcp
sudo ufw reload
clear
